(ns arm_cpu.actor
  "arm_cpu clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Arm CPU core microarchitecture design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; ArmCore
   {:db/ident :arm_cpu.ArmCore/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :arm_cpu.ArmCore/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.ArmCore/isa :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.ArmCore/microarch :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.ArmCore/frequencyGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.ArmCore/issueWidth :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.ArmCore/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.ArmCore/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Cluster
   {:db/ident :arm_cpu.Cluster/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :arm_cpu.Cluster/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Cluster/coreCount :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Cluster/topology :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Cluster/sharedCacheKb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Cluster/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Cluster/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; NeonUnit
   {:db/ident :arm_cpu.NeonUnit/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :arm_cpu.NeonUnit/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.NeonUnit/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.NeonUnit/widthBits :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.NeonUnit/lanes :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.NeonUnit/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.NeonUnit/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; CacheLevel
   {:db/ident :arm_cpu.CacheLevel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :arm_cpu.CacheLevel/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.CacheLevel/level :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.CacheLevel/sizeKb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.CacheLevel/associativity :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.CacheLevel/latencyCycles :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.CacheLevel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.CacheLevel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Interrupt
   {:db/ident :arm_cpu.Interrupt/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :arm_cpu.Interrupt/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Interrupt/controller :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Interrupt/vectors :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Interrupt/priorityBits :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Interrupt/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.Interrupt/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; PowerState
   {:db/ident :arm_cpu.PowerState/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :arm_cpu.PowerState/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.PowerState/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.PowerState/voltageV :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.PowerState/powerMw :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.PowerState/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :arm_cpu.PowerState/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"ArmCore" "Cluster" "NeonUnit" "CacheLevel" "Interrupt" "PowerState"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "arm_cpu: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "arm_cpu: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "arm_cpu: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── ArmCore ────────────────────────────────────────────────────────────────
(defn create-arm-core
  "Create a ArmCore."
  [port data]
  (require-fields data ["name" "isa"])
  (let [id (new-id "acpu_arm")
        e {:db/id id
           :arm_cpu.ArmCore/id id
           :arm_cpu.ArmCore/name (get data :name)
           :arm_cpu.ArmCore/isa (get data :isa)
           :arm_cpu.ArmCore/microarch (get data :microarch)
           :arm_cpu.ArmCore/frequencyGhz (as-double (get data :frequencyGhz))
           :arm_cpu.ArmCore/issueWidth (as-long (get data :issueWidth))
           :arm_cpu.ArmCore/createdAt (now)
           :arm_cpu.ArmCore/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-arm-cores
  "List ArmCore with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-arm-cores port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :arm_cpu.ArmCore/id))
         rows (apply-filters rows (:filter opts) [:arm_cpu.ArmCore/name :arm_cpu.ArmCore/isa :arm_cpu.ArmCore/microarch :arm_cpu.ArmCore/frequencyGhz :arm_cpu.ArmCore/issueWidth])]
     (paginate rows opts))))

(defn get-arm-core
  "Retrieve a ArmCore by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-arm-core port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-arm-core
  "Update a ArmCore; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :arm_cpu.ArmCore/name (get data :name)]))
                   (cond-> (contains? data :isa) (conj [:db/add id :arm_cpu.ArmCore/isa (get data :isa)]))
                   (cond-> (contains? data :microarch) (conj [:db/add id :arm_cpu.ArmCore/microarch (get data :microarch)]))
                   (cond-> (contains? data :frequencyGhz) (conj [:db/add id :arm_cpu.ArmCore/frequencyGhz (as-double (get data :frequencyGhz))]))
                   (cond-> (contains? data :issueWidth) (conj [:db/add id :arm_cpu.ArmCore/issueWidth (as-long (get data :issueWidth))]))
                   (conj [:db/add id :arm_cpu.ArmCore/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-arm-core
  "Delete a ArmCore."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Cluster ────────────────────────────────────────────────────────────────
(defn create-cluster
  "Create a Cluster."
  [port data]
  (require-fields data ["coreCount" "topology"])
  (let [id (new-id "acpu_clu")
        e {:db/id id
           :arm_cpu.Cluster/id id
           :arm_cpu.Cluster/coreId (get data :coreId)
           :arm_cpu.Cluster/coreCount (as-long (get data :coreCount))
           :arm_cpu.Cluster/topology (get data :topology)
           :arm_cpu.Cluster/sharedCacheKb (as-long (get data :sharedCacheKb))
           :arm_cpu.Cluster/createdAt (now)
           :arm_cpu.Cluster/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-clusters
  "List Cluster with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-clusters port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :arm_cpu.Cluster/id))
         rows (apply-filters rows (:filter opts) [:arm_cpu.Cluster/coreId :arm_cpu.Cluster/coreCount :arm_cpu.Cluster/topology :arm_cpu.Cluster/sharedCacheKb])]
     (paginate rows opts))))

(defn get-cluster
  "Retrieve a Cluster by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cluster port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cluster
  "Update a Cluster; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :arm_cpu.Cluster/coreId (get data :coreId)]))
                   (cond-> (contains? data :coreCount) (conj [:db/add id :arm_cpu.Cluster/coreCount (as-long (get data :coreCount))]))
                   (cond-> (contains? data :topology) (conj [:db/add id :arm_cpu.Cluster/topology (get data :topology)]))
                   (cond-> (contains? data :sharedCacheKb) (conj [:db/add id :arm_cpu.Cluster/sharedCacheKb (as-long (get data :sharedCacheKb))]))
                   (conj [:db/add id :arm_cpu.Cluster/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cluster
  "Delete a Cluster."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── NeonUnit ────────────────────────────────────────────────────────────────
(defn create-neon-unit
  "Create a NeonUnit."
  [port data]
  (require-fields data ["kind" "widthBits"])
  (let [id (new-id "acpu_neo")
        e {:db/id id
           :arm_cpu.NeonUnit/id id
           :arm_cpu.NeonUnit/coreId (get data :coreId)
           :arm_cpu.NeonUnit/kind (get data :kind)
           :arm_cpu.NeonUnit/widthBits (as-long (get data :widthBits))
           :arm_cpu.NeonUnit/lanes (as-long (get data :lanes))
           :arm_cpu.NeonUnit/createdAt (now)
           :arm_cpu.NeonUnit/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-neon-units
  "List NeonUnit with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-neon-units port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :arm_cpu.NeonUnit/id))
         rows (apply-filters rows (:filter opts) [:arm_cpu.NeonUnit/coreId :arm_cpu.NeonUnit/kind :arm_cpu.NeonUnit/widthBits :arm_cpu.NeonUnit/lanes])]
     (paginate rows opts))))

(defn get-neon-unit
  "Retrieve a NeonUnit by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-neon-unit port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-neon-unit
  "Update a NeonUnit; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :arm_cpu.NeonUnit/coreId (get data :coreId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :arm_cpu.NeonUnit/kind (get data :kind)]))
                   (cond-> (contains? data :widthBits) (conj [:db/add id :arm_cpu.NeonUnit/widthBits (as-long (get data :widthBits))]))
                   (cond-> (contains? data :lanes) (conj [:db/add id :arm_cpu.NeonUnit/lanes (as-long (get data :lanes))]))
                   (conj [:db/add id :arm_cpu.NeonUnit/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-neon-unit
  "Delete a NeonUnit."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── CacheLevel ────────────────────────────────────────────────────────────────
(defn create-cache-level
  "Create a CacheLevel."
  [port data]
  (require-fields data ["level" "sizeKb"])
  (let [id (new-id "acpu_cac")
        e {:db/id id
           :arm_cpu.CacheLevel/id id
           :arm_cpu.CacheLevel/coreId (get data :coreId)
           :arm_cpu.CacheLevel/level (get data :level)
           :arm_cpu.CacheLevel/sizeKb (as-long (get data :sizeKb))
           :arm_cpu.CacheLevel/associativity (as-long (get data :associativity))
           :arm_cpu.CacheLevel/latencyCycles (as-long (get data :latencyCycles))
           :arm_cpu.CacheLevel/createdAt (now)
           :arm_cpu.CacheLevel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-cache-levels
  "List CacheLevel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-cache-levels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :arm_cpu.CacheLevel/id))
         rows (apply-filters rows (:filter opts) [:arm_cpu.CacheLevel/coreId :arm_cpu.CacheLevel/level :arm_cpu.CacheLevel/sizeKb :arm_cpu.CacheLevel/associativity :arm_cpu.CacheLevel/latencyCycles])]
     (paginate rows opts))))

(defn get-cache-level
  "Retrieve a CacheLevel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cache-level port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cache-level
  "Update a CacheLevel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :arm_cpu.CacheLevel/coreId (get data :coreId)]))
                   (cond-> (contains? data :level) (conj [:db/add id :arm_cpu.CacheLevel/level (get data :level)]))
                   (cond-> (contains? data :sizeKb) (conj [:db/add id :arm_cpu.CacheLevel/sizeKb (as-long (get data :sizeKb))]))
                   (cond-> (contains? data :associativity) (conj [:db/add id :arm_cpu.CacheLevel/associativity (as-long (get data :associativity))]))
                   (cond-> (contains? data :latencyCycles) (conj [:db/add id :arm_cpu.CacheLevel/latencyCycles (as-long (get data :latencyCycles))]))
                   (conj [:db/add id :arm_cpu.CacheLevel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cache-level
  "Delete a CacheLevel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Interrupt ────────────────────────────────────────────────────────────────
(defn create-interrupt
  "Create a Interrupt."
  [port data]
  (require-fields data ["controller" "vectors"])
  (let [id (new-id "acpu_int")
        e {:db/id id
           :arm_cpu.Interrupt/id id
           :arm_cpu.Interrupt/coreId (get data :coreId)
           :arm_cpu.Interrupt/controller (get data :controller)
           :arm_cpu.Interrupt/vectors (as-long (get data :vectors))
           :arm_cpu.Interrupt/priorityBits (as-long (get data :priorityBits))
           :arm_cpu.Interrupt/createdAt (now)
           :arm_cpu.Interrupt/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-interrupts
  "List Interrupt with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-interrupts port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :arm_cpu.Interrupt/id))
         rows (apply-filters rows (:filter opts) [:arm_cpu.Interrupt/coreId :arm_cpu.Interrupt/controller :arm_cpu.Interrupt/vectors :arm_cpu.Interrupt/priorityBits])]
     (paginate rows opts))))

(defn get-interrupt
  "Retrieve a Interrupt by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-interrupt port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-interrupt
  "Update a Interrupt; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :arm_cpu.Interrupt/coreId (get data :coreId)]))
                   (cond-> (contains? data :controller) (conj [:db/add id :arm_cpu.Interrupt/controller (get data :controller)]))
                   (cond-> (contains? data :vectors) (conj [:db/add id :arm_cpu.Interrupt/vectors (as-long (get data :vectors))]))
                   (cond-> (contains? data :priorityBits) (conj [:db/add id :arm_cpu.Interrupt/priorityBits (as-long (get data :priorityBits))]))
                   (conj [:db/add id :arm_cpu.Interrupt/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-interrupt
  "Delete a Interrupt."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── PowerState ────────────────────────────────────────────────────────────────
(defn create-power-state
  "Create a PowerState."
  [port data]
  (require-fields data ["name" "voltageV"])
  (let [id (new-id "acpu_pow")
        e {:db/id id
           :arm_cpu.PowerState/id id
           :arm_cpu.PowerState/coreId (get data :coreId)
           :arm_cpu.PowerState/name (get data :name)
           :arm_cpu.PowerState/voltageV (as-double (get data :voltageV))
           :arm_cpu.PowerState/powerMw (as-double (get data :powerMw))
           :arm_cpu.PowerState/createdAt (now)
           :arm_cpu.PowerState/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-power-states
  "List PowerState with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-power-states port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :arm_cpu.PowerState/id))
         rows (apply-filters rows (:filter opts) [:arm_cpu.PowerState/coreId :arm_cpu.PowerState/name :arm_cpu.PowerState/voltageV :arm_cpu.PowerState/powerMw])]
     (paginate rows opts))))

(defn get-power-state
  "Retrieve a PowerState by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-power-state port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-power-state
  "Update a PowerState; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :arm_cpu.PowerState/coreId (get data :coreId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :arm_cpu.PowerState/name (get data :name)]))
                   (cond-> (contains? data :voltageV) (conj [:db/add id :arm_cpu.PowerState/voltageV (as-double (get data :voltageV))]))
                   (cond-> (contains? data :powerMw) (conj [:db/add id :arm_cpu.PowerState/powerMw (as-double (get data :powerMw))]))
                   (conj [:db/add id :arm_cpu.PowerState/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-power-state
  "Delete a PowerState."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/armcores" :op :create :entity "ArmCore"}
   {:method "GET" :path "/v1/armcores" :op :list :entity "ArmCore"}
   {:method "GET" :path "/v1/armcores/:id" :op :get :entity "ArmCore"}
   {:method "PATCH" :path "/v1/armcores/:id" :op :update :entity "ArmCore"}
   {:method "DELETE" :path "/v1/armcores/:id" :op :delete :entity "ArmCore"}
   {:method "POST" :path "/v1/clusters" :op :create :entity "Cluster"}
   {:method "GET" :path "/v1/clusters" :op :list :entity "Cluster"}
   {:method "GET" :path "/v1/clusters/:id" :op :get :entity "Cluster"}
   {:method "PATCH" :path "/v1/clusters/:id" :op :update :entity "Cluster"}
   {:method "DELETE" :path "/v1/clusters/:id" :op :delete :entity "Cluster"}
   {:method "POST" :path "/v1/neonunits" :op :create :entity "NeonUnit"}
   {:method "GET" :path "/v1/neonunits" :op :list :entity "NeonUnit"}
   {:method "GET" :path "/v1/neonunits/:id" :op :get :entity "NeonUnit"}
   {:method "PATCH" :path "/v1/neonunits/:id" :op :update :entity "NeonUnit"}
   {:method "DELETE" :path "/v1/neonunits/:id" :op :delete :entity "NeonUnit"}
   {:method "POST" :path "/v1/cachelevels" :op :create :entity "CacheLevel"}
   {:method "GET" :path "/v1/cachelevels" :op :list :entity "CacheLevel"}
   {:method "GET" :path "/v1/cachelevels/:id" :op :get :entity "CacheLevel"}
   {:method "PATCH" :path "/v1/cachelevels/:id" :op :update :entity "CacheLevel"}
   {:method "DELETE" :path "/v1/cachelevels/:id" :op :delete :entity "CacheLevel"}
   {:method "POST" :path "/v1/interrupts" :op :create :entity "Interrupt"}
   {:method "GET" :path "/v1/interrupts" :op :list :entity "Interrupt"}
   {:method "GET" :path "/v1/interrupts/:id" :op :get :entity "Interrupt"}
   {:method "PATCH" :path "/v1/interrupts/:id" :op :update :entity "Interrupt"}
   {:method "DELETE" :path "/v1/interrupts/:id" :op :delete :entity "Interrupt"}
   {:method "POST" :path "/v1/powerstates" :op :create :entity "PowerState"}
   {:method "GET" :path "/v1/powerstates" :op :list :entity "PowerState"}
   {:method "GET" :path "/v1/powerstates/:id" :op :get :entity "PowerState"}
   {:method "PATCH" :path "/v1/powerstates/:id" :op :update :entity "PowerState"}
   {:method "DELETE" :path "/v1/powerstates/:id" :op :delete :entity "PowerState"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"armcores" {:create create-arm-core :list list-arm-cores :get get-arm-core :update update-arm-core :delete delete-arm-core}
   "clusters" {:create create-cluster :list list-clusters :get get-cluster :update update-cluster :delete delete-cluster}
   "neonunits" {:create create-neon-unit :list list-neon-units :get get-neon-unit :update update-neon-unit :delete delete-neon-unit}
   "cachelevels" {:create create-cache-level :list list-cache-levels :get get-cache-level :update update-cache-level :delete delete-cache-level}
   "interrupts" {:create create-interrupt :list list-interrupts :get get-interrupt :update update-interrupt :delete delete-interrupt}
   "powerstates" {:create create-power-state :list list-power-states :get get-power-state :update update-power-state :delete delete-power-state}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "arm_cpu-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
